// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgDmHdE9973IKuNkWGEIocTFgxkQlUYbU',
    appId: '1:1016672011158:web:062a71c9df9b25623bd3b7',
    messagingSenderId: '1016672011158',
    projectId: 'vertexai-firebase-2025',
    authDomain: 'vertexai-firebase-2025.firebaseapp.com',
    storageBucket: 'vertexai-firebase-2025.firebasestorage.app',
    measurementId: 'G-MKDXWD6TXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlAcr9LFdHYGJcFPXfQLhFOLdP278KL34',
    appId: '1:1016672011158:android:29605a271297142f3bd3b7',
    messagingSenderId: '1016672011158',
    projectId: 'vertexai-firebase-2025',
    storageBucket: 'vertexai-firebase-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhuzIvcqswh2vrQYpsfGExIoVQiaCDhSE',
    appId: '1:1016672011158:ios:5343fd514f3497033bd3b7',
    messagingSenderId: '1016672011158',
    projectId: 'vertexai-firebase-2025',
    storageBucket: 'vertexai-firebase-2025.firebasestorage.app',
    iosBundleId: 'com.example.fireflutDemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhuzIvcqswh2vrQYpsfGExIoVQiaCDhSE',
    appId: '1:1016672011158:ios:5343fd514f3497033bd3b7',
    messagingSenderId: '1016672011158',
    projectId: 'vertexai-firebase-2025',
    storageBucket: 'vertexai-firebase-2025.firebasestorage.app',
    iosBundleId: 'com.example.fireflutDemoApp',
  );
}
